class WineData {
  String productImg, productName, color, country, price, description;

  WineData(this.productImg, this.productName, this.color, this.country,
      this.price, this.description);

  static List<WineData> WineInfo() {
    return [
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum"),
    ];
  }
}
